const response = await fetch('/VRMLViewer/wrl/cube.wrl')
const text = await response.text()
const positionPoint = text.indexOf('point')
const positionPointStart = text.indexOf('[', positionPoint)
const positionPointEnd = text.indexOf(']', positionPoint)
const textPoint = text.substring(positionPointStart + 1, positionPointEnd)
const points = textPoint.trim().split(/[\s,]+/)
console.log('points', points)